name: MasterCI
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Copy file via scp
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.F3AQA2_HOST }}
          username: tiger
          key: ${{ secrets.F3AQA2_SSH_KEY }}
          source: "./src/test.sh"
          target: "test"

