name: MasterCI
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: executing remote ssh commands using ssh key
        uses: appleboy/ssh-action@master
        with:
          local: ./src/test.sh
          remote: scp/src/test.sh
          command: ./src/test.sh
          host: ${{ secrets.F3AQA2_HOST }}
          username: tiger
          key: ${{ secrets.F3AQA2_SSH_KEY }}
