name: MasterCI
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: set env
        run : |
          echo "::set-env name=REMOTE_DIR::/tmp/github-action.test.d"

      - name: Copy file via scp
        uses: appleboy/scp-action@master
        with:
          # ssh connect
          username : namgivu
          host     : ${{ secrets.REMOTE_HOST }}
          key      : ${{ secrets.REMOTE_SSH_KEY }}
          # file to copy
          source : ./src/test.sh
          target : ${{ env.REMOTE_DIR }}

      - name: Executing remote command
        uses: appleboy/ssh-action@master
        with:
          # ssh connect
          username : namgivu
          host     : ${{ secrets.REMOTE_HOST }}
          key      : ${{ secrets.REMOTE_SSH_KEY }}
          # script to run
          script: ${{ env.REMOTE_DIR }}/src/test.sh
